version: '3'

vars:
  GREEN: "\033[0;32m"
  BLUE: "\033[0;34m"
  RED: "\033[0;31m"
  YELLOW: "\033[0;33m"
  NC: "\033[0m" # No Color / Reset

tasks:
  init:
    desc: "Initialize the environment: Clone repos if missing and install requisites."
    silent: true
    cmds:
      - |
        if [ ! -d "../frontend-boti" ]; then
          echo "Cloning frontend..."
          cd .. && git clone https://github.com/IA-UD-Tech/frontend-boti.git
        else
          echo -e "${RED}Frontend already exists. Skipping clone.${NC}"
        fi
      - |
        if [ ! -d "../backend-boti" ]; then
          echo "Cloning backend..."
          cd ..&& git clone https://github.com/IA-UD-Tech/backend-boti.git
        else
          echo "Backend already exists. Skipping clone."
        fi
        # cd ../backend-boti && 
      - |
        echo "Installing prerequisites..."
        ./scripts/install-deps.sh
      - |
        echo -e "${GREEN}Creating common network...${NC}"
        docker network create boti-net || true

  start:
    desc: "Start the environment: Start the backend and frontend."
    silent: true
    vars:
      REBUILD: false
    cmds:
      - |
        if [ "$REBUILD" = true ]; then
        echo -e "${GREEN}Rebuilding backend...${NC}"
        cd ../backend-boti && docker-compose up -d --build
        else
        echo -e "${GREEN}Starting backend...${NC}"
        cd ../backend-boti && docker-compose up -d
        fi
      - |
        if [ "$REBUILD" = true ]; then
        echo -e "${GREEN}Rebuilding frontend...${NC}"
        cd ../frontend-boti && docker-compose up -d --build
        else
        echo -e "${GREEN}Starting frontend...${NC}"
        cd ../frontend-boti && docker-compose up -d
        fi

  stop:
    desc: "Stop the environment: Stop the backend and frontend."
    silent: true
    cmds:
      - |
        echo -e "${RED}Stopping frontend...${NC}"
        cd ../frontend-boti && docker-compose down
      - |
        echo -e "${RED}Stopping backend...${NC}"
        cd ../backend-boti && docker-compose down
